name: Terraform Deploy to AWS

on:
  workflow_dispatch:  # Manual trigger 
  # push:
  #   branches:
  #     - main  # or your deployment branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2  # or use ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0  # or your preferred version
    
    # ✅ Restore cache (state file)
    - name: Restore Terraform State Cache
      uses: actions/cache@v4
      with:
        path: terraform.tfstate
        key: terraform-state-${{ github.ref }}
        restore-keys: terraform-state-
     
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    # ✅ Save updated state file to cache
    - name: Save Terraform State Cache
      uses: actions/cache@v4
      with:
        path: terraform.tfstate
        key: terraform-state-${{ github.run_id }}  # unique key for saving
        save-always: true

    # ✅ Upload state file as artifact
    # - name: Upload Terraform State
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: terraform-state
    #     path: terraform.tfstate
   
